apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python-test
spec:
  containers:
  - image: marcinkujawski/python-api:1.0
    name: python-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
