apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test-pod3
spec:
  containers:
  - image: nginx
    name: cont1 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
