apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: nfs-pv
spec:
  storageClassName: "nfs-class" # optional
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs-share
    server: 172.16.2.112
  persistentVolumeReclaimPolicy: Retain
