apiVersion: v1
kind: Pod
metadata:
  name: secret-pod2
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done" ]
      volumeMounts:
        - name: secret
          mountPath: /etc/config
  volumes:
    - name: secret
      secret:
        secretName: my-password
