apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
