apiVersion: v1
kind: Pod
metadata:
  name: slow-sc-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: slow-sc-pvc
